imports:
- path: vpccreation-template.jinja
- path: firewall-template.jinja
- path: privatesubnetwork-template.jinja
- path: publicsubnetwork-template.jinja
- path: googlecompute-template.jinja
- path: routecreation-template.jinja
- path: http-httpsfirewall-template.jinja

resources:
- name: network-setup
  type: googlecompute-template.jinja
